name = "sundae/contracts"
version = "0.0.0"
license = "Apache-2.0"
description = "Experimental port of SundaeSwap to Aiken"

[repository]
user = "sundae"
project = "contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "97cd61345bcc8925c521b30d0f354859eb0148cd"
source = "github"

[[dependencies]]
name = "SundaeSwap-finance/aicone"
version = "ae0852d40cc6332437492102451cf331a3c10b0d"
source = "github"

[[dependencies]]
name = "aiken-extra/tx_util"
version = "1.170.202312"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"